# syntax=docker/dockerfile:1

# Builder stage: install deps, generate Prisma client and build the app
FROM node:20-alpine AS builder

WORKDIR /app

# Install build tools
RUN apk add --no-cache --virtual .gyp python3 make g++

# Copy package manifests first for better layer caching
COPY package.json package-lock.json* ./

# Install dependencies (including devDeps needed to build)
RUN npm ci

# Copy rest of the sources
COPY . .

# Generate Prisma client (if you use prisma generate in your workflow)
RUN npx prisma generate || true

# Build the application (Nest will compile to /dist)
RUN npm run build

# Remove build tools and dev dependencies to shrink image
RUN npm prune --production && apk del .gyp || true


# Production image
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copy production node_modules and built dist from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json

# If you keep runtime artifacts generated by prisma (optional), copy them too
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/generated ./generated

EXPOSE 3000

# Use the compiled entrypoint generated by Nest

CMD ["node", "dist/src/main.js"]
